// <auto-generated/>
#pragma warning disable CS0618
using Immich.Client.Activities;
using Immich.Client.Admin;
using Immich.Client.Albums;
using Immich.Client.ApiKeys;
using Immich.Client.Assets;
using Immich.Client.Auth;
using Immich.Client.Download;
using Immich.Client.Duplicates;
using Immich.Client.Faces;
using Immich.Client.Jobs;
using Immich.Client.Libraries;
using Immich.Client.Map;
using Immich.Client.Memories;
using Immich.Client.Notifications;
using Immich.Client.Oauth;
using Immich.Client.Partners;
using Immich.Client.People;
using Immich.Client.Search;
using Immich.Client.Server;
using Immich.Client.Sessions;
using Immich.Client.SharedLinks;
using Immich.Client.Stacks;
using Immich.Client.Sync;
using Immich.Client.SystemConfig;
using Immich.Client.SystemMetadata;
using Immich.Client.Tags;
using Immich.Client.Timeline;
using Immich.Client.Trash;
using Immich.Client.Users;
using Immich.Client.View;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImmichClient : BaseRequestBuilder
    {
        /// <summary>The activities property</summary>
        public global::Immich.Client.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Immich.Client.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The admin property</summary>
        public global::Immich.Client.Admin.AdminRequestBuilder Admin
        {
            get => new global::Immich.Client.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The albums property</summary>
        public global::Immich.Client.Albums.AlbumsRequestBuilder Albums
        {
            get => new global::Immich.Client.Albums.AlbumsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apiKeys property</summary>
        public global::Immich.Client.ApiKeys.ApiKeysRequestBuilder ApiKeys
        {
            get => new global::Immich.Client.ApiKeys.ApiKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::Immich.Client.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Immich.Client.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Immich.Client.Auth.AuthRequestBuilder Auth
        {
            get => new global::Immich.Client.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::Immich.Client.Download.DownloadRequestBuilder Download
        {
            get => new global::Immich.Client.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The duplicates property</summary>
        public global::Immich.Client.Duplicates.DuplicatesRequestBuilder Duplicates
        {
            get => new global::Immich.Client.Duplicates.DuplicatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The faces property</summary>
        public global::Immich.Client.Faces.FacesRequestBuilder Faces
        {
            get => new global::Immich.Client.Faces.FacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Immich.Client.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Immich.Client.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The libraries property</summary>
        public global::Immich.Client.Libraries.LibrariesRequestBuilder Libraries
        {
            get => new global::Immich.Client.Libraries.LibrariesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The map property</summary>
        public global::Immich.Client.Map.MapRequestBuilder Map
        {
            get => new global::Immich.Client.Map.MapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memories property</summary>
        public global::Immich.Client.Memories.MemoriesRequestBuilder Memories
        {
            get => new global::Immich.Client.Memories.MemoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Immich.Client.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Immich.Client.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Immich.Client.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Immich.Client.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partners property</summary>
        public global::Immich.Client.Partners.PartnersRequestBuilder Partners
        {
            get => new global::Immich.Client.Partners.PartnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public global::Immich.Client.People.PeopleRequestBuilder People
        {
            get => new global::Immich.Client.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Immich.Client.Search.SearchRequestBuilder Search
        {
            get => new global::Immich.Client.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The server property</summary>
        public global::Immich.Client.Server.ServerRequestBuilder Server
        {
            get => new global::Immich.Client.Server.ServerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Immich.Client.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Immich.Client.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sharedLinks property</summary>
        public global::Immich.Client.SharedLinks.SharedLinksRequestBuilder SharedLinks
        {
            get => new global::Immich.Client.SharedLinks.SharedLinksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stacks property</summary>
        public global::Immich.Client.Stacks.StacksRequestBuilder Stacks
        {
            get => new global::Immich.Client.Stacks.StacksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Immich.Client.Sync.SyncRequestBuilder Sync
        {
            get => new global::Immich.Client.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systemConfig property</summary>
        public global::Immich.Client.SystemConfig.SystemConfigRequestBuilder SystemConfig
        {
            get => new global::Immich.Client.SystemConfig.SystemConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systemMetadata property</summary>
        public global::Immich.Client.SystemMetadata.SystemMetadataRequestBuilder SystemMetadata
        {
            get => new global::Immich.Client.SystemMetadata.SystemMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Immich.Client.Tags.TagsRequestBuilder Tags
        {
            get => new global::Immich.Client.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timeline property</summary>
        public global::Immich.Client.Timeline.TimelineRequestBuilder Timeline
        {
            get => new global::Immich.Client.Timeline.TimelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trash property</summary>
        public global::Immich.Client.Trash.TrashRequestBuilder Trash
        {
            get => new global::Immich.Client.Trash.TrashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Immich.Client.Users.UsersRequestBuilder Users
        {
            get => new global::Immich.Client.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The view property</summary>
        public global::Immich.Client.View.ViewRequestBuilder View
        {
            get => new global::Immich.Client.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.ImmichClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImmichClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "/api";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
