// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllJobStatusResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backgroundTask property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? BackgroundTask { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto BackgroundTask { get; set; }
#endif
        /// <summary>The backupDatabase property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? BackupDatabase { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto BackupDatabase { get; set; }
#endif
        /// <summary>The duplicateDetection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? DuplicateDetection { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto DuplicateDetection { get; set; }
#endif
        /// <summary>The faceDetection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? FaceDetection { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto FaceDetection { get; set; }
#endif
        /// <summary>The facialRecognition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? FacialRecognition { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto FacialRecognition { get; set; }
#endif
        /// <summary>The library property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? Library { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto Library { get; set; }
#endif
        /// <summary>The metadataExtraction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? MetadataExtraction { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto MetadataExtraction { get; set; }
#endif
        /// <summary>The migration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? Migration { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto Migration { get; set; }
#endif
        /// <summary>The notifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? Notifications { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto Notifications { get; set; }
#endif
        /// <summary>The search property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? Search { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto Search { get; set; }
#endif
        /// <summary>The sidecar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? Sidecar { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto Sidecar { get; set; }
#endif
        /// <summary>The smartSearch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? SmartSearch { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto SmartSearch { get; set; }
#endif
        /// <summary>The storageTemplateMigration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? StorageTemplateMigration { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto StorageTemplateMigration { get; set; }
#endif
        /// <summary>The thumbnailGeneration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? ThumbnailGeneration { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto ThumbnailGeneration { get; set; }
#endif
        /// <summary>The videoConversion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobStatusDto? VideoConversion { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobStatusDto VideoConversion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Models.AllJobStatusResponseDto"/> and sets the default values.
        /// </summary>
        public AllJobStatusResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Immich.Client.Models.AllJobStatusResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Immich.Client.Models.AllJobStatusResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Immich.Client.Models.AllJobStatusResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backgroundTask", n => { BackgroundTask = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "backupDatabase", n => { BackupDatabase = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "duplicateDetection", n => { DuplicateDetection = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "faceDetection", n => { FaceDetection = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "facialRecognition", n => { FacialRecognition = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "library", n => { Library = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "metadataExtraction", n => { MetadataExtraction = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "migration", n => { Migration = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "notifications", n => { Notifications = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "search", n => { Search = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "sidecar", n => { Sidecar = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "smartSearch", n => { SmartSearch = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "storageTemplateMigration", n => { StorageTemplateMigration = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "thumbnailGeneration", n => { ThumbnailGeneration = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
                { "videoConversion", n => { VideoConversion = n.GetObjectValue<global::Immich.Client.Models.JobStatusDto>(global::Immich.Client.Models.JobStatusDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("backgroundTask", BackgroundTask);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("backupDatabase", BackupDatabase);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("duplicateDetection", DuplicateDetection);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("faceDetection", FaceDetection);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("facialRecognition", FacialRecognition);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("library", Library);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("metadataExtraction", MetadataExtraction);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("migration", Migration);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("notifications", Notifications);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("search", Search);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("sidecar", Sidecar);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("smartSearch", SmartSearch);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("storageTemplateMigration", StorageTemplateMigration);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("thumbnailGeneration", ThumbnailGeneration);
            writer.WriteObjectValue<global::Immich.Client.Models.JobStatusDto>("videoConversion", VideoConversion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
