// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AssetMetadataKey
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mobile-app")]
        #pragma warning disable CS1591
        MobileApp,
        #pragma warning restore CS1591
    }
}
