// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemConfigDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigBackupsDto? Backup { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigBackupsDto Backup { get; set; }
#endif
        /// <summary>The ffmpeg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigFFmpegDto? Ffmpeg { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigFFmpegDto Ffmpeg { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigImageDto? Image { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigImageDto Image { get; set; }
#endif
        /// <summary>The job property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigJobDto? Job { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigJobDto Job { get; set; }
#endif
        /// <summary>The library property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigLibraryDto? Library { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigLibraryDto Library { get; set; }
#endif
        /// <summary>The logging property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigLoggingDto? Logging { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigLoggingDto Logging { get; set; }
#endif
        /// <summary>The machineLearning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigMachineLearningDto? MachineLearning { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigMachineLearningDto MachineLearning { get; set; }
#endif
        /// <summary>The map property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigMapDto? Map { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigMapDto Map { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigMetadataDto? Metadata { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigMetadataDto Metadata { get; set; }
#endif
        /// <summary>The newVersionCheck property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigNewVersionCheckDto? NewVersionCheck { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigNewVersionCheckDto NewVersionCheck { get; set; }
#endif
        /// <summary>The nightlyTasks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigNightlyTasksDto? NightlyTasks { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigNightlyTasksDto NightlyTasks { get; set; }
#endif
        /// <summary>The notifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigNotificationsDto? Notifications { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigNotificationsDto Notifications { get; set; }
#endif
        /// <summary>The oauth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigOAuthDto? Oauth { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigOAuthDto Oauth { get; set; }
#endif
        /// <summary>The passwordLogin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigPasswordLoginDto? PasswordLogin { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigPasswordLoginDto PasswordLogin { get; set; }
#endif
        /// <summary>The reverseGeocoding property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigReverseGeocodingDto? ReverseGeocoding { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigReverseGeocodingDto ReverseGeocoding { get; set; }
#endif
        /// <summary>The server property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigServerDto? Server { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigServerDto Server { get; set; }
#endif
        /// <summary>The storageTemplate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigStorageTemplateDto? StorageTemplate { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigStorageTemplateDto StorageTemplate { get; set; }
#endif
        /// <summary>The templates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigTemplatesDto? Templates { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigTemplatesDto Templates { get; set; }
#endif
        /// <summary>The theme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigThemeDto? Theme { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigThemeDto Theme { get; set; }
#endif
        /// <summary>The trash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigTrashDto? Trash { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigTrashDto Trash { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SystemConfigUserDto? User { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SystemConfigUserDto User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Models.SystemConfigDto"/> and sets the default values.
        /// </summary>
        public SystemConfigDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Immich.Client.Models.SystemConfigDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Immich.Client.Models.SystemConfigDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Immich.Client.Models.SystemConfigDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup", n => { Backup = n.GetObjectValue<global::Immich.Client.Models.SystemConfigBackupsDto>(global::Immich.Client.Models.SystemConfigBackupsDto.CreateFromDiscriminatorValue); } },
                { "ffmpeg", n => { Ffmpeg = n.GetObjectValue<global::Immich.Client.Models.SystemConfigFFmpegDto>(global::Immich.Client.Models.SystemConfigFFmpegDto.CreateFromDiscriminatorValue); } },
                { "image", n => { Image = n.GetObjectValue<global::Immich.Client.Models.SystemConfigImageDto>(global::Immich.Client.Models.SystemConfigImageDto.CreateFromDiscriminatorValue); } },
                { "job", n => { Job = n.GetObjectValue<global::Immich.Client.Models.SystemConfigJobDto>(global::Immich.Client.Models.SystemConfigJobDto.CreateFromDiscriminatorValue); } },
                { "library", n => { Library = n.GetObjectValue<global::Immich.Client.Models.SystemConfigLibraryDto>(global::Immich.Client.Models.SystemConfigLibraryDto.CreateFromDiscriminatorValue); } },
                { "logging", n => { Logging = n.GetObjectValue<global::Immich.Client.Models.SystemConfigLoggingDto>(global::Immich.Client.Models.SystemConfigLoggingDto.CreateFromDiscriminatorValue); } },
                { "machineLearning", n => { MachineLearning = n.GetObjectValue<global::Immich.Client.Models.SystemConfigMachineLearningDto>(global::Immich.Client.Models.SystemConfigMachineLearningDto.CreateFromDiscriminatorValue); } },
                { "map", n => { Map = n.GetObjectValue<global::Immich.Client.Models.SystemConfigMapDto>(global::Immich.Client.Models.SystemConfigMapDto.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Immich.Client.Models.SystemConfigMetadataDto>(global::Immich.Client.Models.SystemConfigMetadataDto.CreateFromDiscriminatorValue); } },
                { "newVersionCheck", n => { NewVersionCheck = n.GetObjectValue<global::Immich.Client.Models.SystemConfigNewVersionCheckDto>(global::Immich.Client.Models.SystemConfigNewVersionCheckDto.CreateFromDiscriminatorValue); } },
                { "nightlyTasks", n => { NightlyTasks = n.GetObjectValue<global::Immich.Client.Models.SystemConfigNightlyTasksDto>(global::Immich.Client.Models.SystemConfigNightlyTasksDto.CreateFromDiscriminatorValue); } },
                { "notifications", n => { Notifications = n.GetObjectValue<global::Immich.Client.Models.SystemConfigNotificationsDto>(global::Immich.Client.Models.SystemConfigNotificationsDto.CreateFromDiscriminatorValue); } },
                { "oauth", n => { Oauth = n.GetObjectValue<global::Immich.Client.Models.SystemConfigOAuthDto>(global::Immich.Client.Models.SystemConfigOAuthDto.CreateFromDiscriminatorValue); } },
                { "passwordLogin", n => { PasswordLogin = n.GetObjectValue<global::Immich.Client.Models.SystemConfigPasswordLoginDto>(global::Immich.Client.Models.SystemConfigPasswordLoginDto.CreateFromDiscriminatorValue); } },
                { "reverseGeocoding", n => { ReverseGeocoding = n.GetObjectValue<global::Immich.Client.Models.SystemConfigReverseGeocodingDto>(global::Immich.Client.Models.SystemConfigReverseGeocodingDto.CreateFromDiscriminatorValue); } },
                { "server", n => { Server = n.GetObjectValue<global::Immich.Client.Models.SystemConfigServerDto>(global::Immich.Client.Models.SystemConfigServerDto.CreateFromDiscriminatorValue); } },
                { "storageTemplate", n => { StorageTemplate = n.GetObjectValue<global::Immich.Client.Models.SystemConfigStorageTemplateDto>(global::Immich.Client.Models.SystemConfigStorageTemplateDto.CreateFromDiscriminatorValue); } },
                { "templates", n => { Templates = n.GetObjectValue<global::Immich.Client.Models.SystemConfigTemplatesDto>(global::Immich.Client.Models.SystemConfigTemplatesDto.CreateFromDiscriminatorValue); } },
                { "theme", n => { Theme = n.GetObjectValue<global::Immich.Client.Models.SystemConfigThemeDto>(global::Immich.Client.Models.SystemConfigThemeDto.CreateFromDiscriminatorValue); } },
                { "trash", n => { Trash = n.GetObjectValue<global::Immich.Client.Models.SystemConfigTrashDto>(global::Immich.Client.Models.SystemConfigTrashDto.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetObjectValue<global::Immich.Client.Models.SystemConfigUserDto>(global::Immich.Client.Models.SystemConfigUserDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigBackupsDto>("backup", Backup);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigFFmpegDto>("ffmpeg", Ffmpeg);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigImageDto>("image", Image);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigJobDto>("job", Job);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigLibraryDto>("library", Library);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigLoggingDto>("logging", Logging);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigMachineLearningDto>("machineLearning", MachineLearning);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigMapDto>("map", Map);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigMetadataDto>("metadata", Metadata);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigNewVersionCheckDto>("newVersionCheck", NewVersionCheck);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigNightlyTasksDto>("nightlyTasks", NightlyTasks);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigNotificationsDto>("notifications", Notifications);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigOAuthDto>("oauth", Oauth);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigPasswordLoginDto>("passwordLogin", PasswordLogin);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigReverseGeocodingDto>("reverseGeocoding", ReverseGeocoding);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigServerDto>("server", Server);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigStorageTemplateDto>("storageTemplate", StorageTemplate);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigTemplatesDto>("templates", Templates);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigThemeDto>("theme", Theme);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigTrashDto>("trash", Trash);
            writer.WriteObjectValue<global::Immich.Client.Models.SystemConfigUserDto>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
