// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemConfigJobDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backgroundTask property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? BackgroundTask { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto BackgroundTask { get; set; }
#endif
        /// <summary>The faceDetection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? FaceDetection { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto FaceDetection { get; set; }
#endif
        /// <summary>The library property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? Library { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto Library { get; set; }
#endif
        /// <summary>The metadataExtraction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? MetadataExtraction { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto MetadataExtraction { get; set; }
#endif
        /// <summary>The migration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? Migration { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto Migration { get; set; }
#endif
        /// <summary>The notifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? Notifications { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto Notifications { get; set; }
#endif
        /// <summary>The search property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? Search { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto Search { get; set; }
#endif
        /// <summary>The sidecar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? Sidecar { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto Sidecar { get; set; }
#endif
        /// <summary>The smartSearch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? SmartSearch { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto SmartSearch { get; set; }
#endif
        /// <summary>The thumbnailGeneration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? ThumbnailGeneration { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto ThumbnailGeneration { get; set; }
#endif
        /// <summary>The videoConversion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.JobSettingsDto? VideoConversion { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.JobSettingsDto VideoConversion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Models.SystemConfigJobDto"/> and sets the default values.
        /// </summary>
        public SystemConfigJobDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Immich.Client.Models.SystemConfigJobDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Immich.Client.Models.SystemConfigJobDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Immich.Client.Models.SystemConfigJobDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backgroundTask", n => { BackgroundTask = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "faceDetection", n => { FaceDetection = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "library", n => { Library = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "metadataExtraction", n => { MetadataExtraction = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "migration", n => { Migration = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "notifications", n => { Notifications = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "search", n => { Search = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "sidecar", n => { Sidecar = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "smartSearch", n => { SmartSearch = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "thumbnailGeneration", n => { ThumbnailGeneration = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
                { "videoConversion", n => { VideoConversion = n.GetObjectValue<global::Immich.Client.Models.JobSettingsDto>(global::Immich.Client.Models.JobSettingsDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("backgroundTask", BackgroundTask);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("faceDetection", FaceDetection);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("library", Library);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("metadataExtraction", MetadataExtraction);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("migration", Migration);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("notifications", Notifications);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("search", Search);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("sidecar", Sidecar);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("smartSearch", SmartSearch);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("thumbnailGeneration", ThumbnailGeneration);
            writer.WriteObjectValue<global::Immich.Client.Models.JobSettingsDto>("videoConversion", VideoConversion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
