// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserPreferencesResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The albums property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.AlbumsResponse? Albums { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.AlbumsResponse Albums { get; set; }
#endif
        /// <summary>The cast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.CastResponse? Cast { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.CastResponse Cast { get; set; }
#endif
        /// <summary>The download property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.DownloadResponse? Download { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.DownloadResponse Download { get; set; }
#endif
        /// <summary>The emailNotifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.EmailNotificationsResponse? EmailNotifications { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.EmailNotificationsResponse EmailNotifications { get; set; }
#endif
        /// <summary>The folders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.FoldersResponse? Folders { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.FoldersResponse Folders { get; set; }
#endif
        /// <summary>The memories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.MemoriesResponse? Memories { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.MemoriesResponse Memories { get; set; }
#endif
        /// <summary>The people property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.PeopleResponse? People { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.PeopleResponse People { get; set; }
#endif
        /// <summary>The purchase property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.PurchaseResponse? Purchase { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.PurchaseResponse Purchase { get; set; }
#endif
        /// <summary>The ratings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.RatingsResponse? Ratings { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.RatingsResponse Ratings { get; set; }
#endif
        /// <summary>The sharedLinks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SharedLinksResponse? SharedLinks { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SharedLinksResponse SharedLinks { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.TagsResponse? Tags { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.TagsResponse Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Models.UserPreferencesResponseDto"/> and sets the default values.
        /// </summary>
        public UserPreferencesResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Immich.Client.Models.UserPreferencesResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Immich.Client.Models.UserPreferencesResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Immich.Client.Models.UserPreferencesResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albums", n => { Albums = n.GetObjectValue<global::Immich.Client.Models.AlbumsResponse>(global::Immich.Client.Models.AlbumsResponse.CreateFromDiscriminatorValue); } },
                { "cast", n => { Cast = n.GetObjectValue<global::Immich.Client.Models.CastResponse>(global::Immich.Client.Models.CastResponse.CreateFromDiscriminatorValue); } },
                { "download", n => { Download = n.GetObjectValue<global::Immich.Client.Models.DownloadResponse>(global::Immich.Client.Models.DownloadResponse.CreateFromDiscriminatorValue); } },
                { "emailNotifications", n => { EmailNotifications = n.GetObjectValue<global::Immich.Client.Models.EmailNotificationsResponse>(global::Immich.Client.Models.EmailNotificationsResponse.CreateFromDiscriminatorValue); } },
                { "folders", n => { Folders = n.GetObjectValue<global::Immich.Client.Models.FoldersResponse>(global::Immich.Client.Models.FoldersResponse.CreateFromDiscriminatorValue); } },
                { "memories", n => { Memories = n.GetObjectValue<global::Immich.Client.Models.MemoriesResponse>(global::Immich.Client.Models.MemoriesResponse.CreateFromDiscriminatorValue); } },
                { "people", n => { People = n.GetObjectValue<global::Immich.Client.Models.PeopleResponse>(global::Immich.Client.Models.PeopleResponse.CreateFromDiscriminatorValue); } },
                { "purchase", n => { Purchase = n.GetObjectValue<global::Immich.Client.Models.PurchaseResponse>(global::Immich.Client.Models.PurchaseResponse.CreateFromDiscriminatorValue); } },
                { "ratings", n => { Ratings = n.GetObjectValue<global::Immich.Client.Models.RatingsResponse>(global::Immich.Client.Models.RatingsResponse.CreateFromDiscriminatorValue); } },
                { "sharedLinks", n => { SharedLinks = n.GetObjectValue<global::Immich.Client.Models.SharedLinksResponse>(global::Immich.Client.Models.SharedLinksResponse.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Immich.Client.Models.TagsResponse>(global::Immich.Client.Models.TagsResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Immich.Client.Models.AlbumsResponse>("albums", Albums);
            writer.WriteObjectValue<global::Immich.Client.Models.CastResponse>("cast", Cast);
            writer.WriteObjectValue<global::Immich.Client.Models.DownloadResponse>("download", Download);
            writer.WriteObjectValue<global::Immich.Client.Models.EmailNotificationsResponse>("emailNotifications", EmailNotifications);
            writer.WriteObjectValue<global::Immich.Client.Models.FoldersResponse>("folders", Folders);
            writer.WriteObjectValue<global::Immich.Client.Models.MemoriesResponse>("memories", Memories);
            writer.WriteObjectValue<global::Immich.Client.Models.PeopleResponse>("people", People);
            writer.WriteObjectValue<global::Immich.Client.Models.PurchaseResponse>("purchase", Purchase);
            writer.WriteObjectValue<global::Immich.Client.Models.RatingsResponse>("ratings", Ratings);
            writer.WriteObjectValue<global::Immich.Client.Models.SharedLinksResponse>("sharedLinks", SharedLinks);
            writer.WriteObjectValue<global::Immich.Client.Models.TagsResponse>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
