// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Immich.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserPreferencesUpdateDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The albums property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.AlbumsUpdate? Albums { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.AlbumsUpdate Albums { get; set; }
#endif
        /// <summary>The avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.AvatarUpdate? Avatar { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.AvatarUpdate Avatar { get; set; }
#endif
        /// <summary>The cast property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.CastUpdate? Cast { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.CastUpdate Cast { get; set; }
#endif
        /// <summary>The download property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.DownloadUpdate? Download { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.DownloadUpdate Download { get; set; }
#endif
        /// <summary>The emailNotifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.EmailNotificationsUpdate? EmailNotifications { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.EmailNotificationsUpdate EmailNotifications { get; set; }
#endif
        /// <summary>The folders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.FoldersUpdate? Folders { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.FoldersUpdate Folders { get; set; }
#endif
        /// <summary>The memories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.MemoriesUpdate? Memories { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.MemoriesUpdate Memories { get; set; }
#endif
        /// <summary>The people property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.PeopleUpdate? People { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.PeopleUpdate People { get; set; }
#endif
        /// <summary>The purchase property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.PurchaseUpdate? Purchase { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.PurchaseUpdate Purchase { get; set; }
#endif
        /// <summary>The ratings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.RatingsUpdate? Ratings { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.RatingsUpdate Ratings { get; set; }
#endif
        /// <summary>The sharedLinks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.SharedLinksUpdate? SharedLinks { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.SharedLinksUpdate SharedLinks { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Immich.Client.Models.TagsUpdate? Tags { get; set; }
#nullable restore
#else
        public global::Immich.Client.Models.TagsUpdate Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Models.UserPreferencesUpdateDto"/> and sets the default values.
        /// </summary>
        public UserPreferencesUpdateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Immich.Client.Models.UserPreferencesUpdateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Immich.Client.Models.UserPreferencesUpdateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Immich.Client.Models.UserPreferencesUpdateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albums", n => { Albums = n.GetObjectValue<global::Immich.Client.Models.AlbumsUpdate>(global::Immich.Client.Models.AlbumsUpdate.CreateFromDiscriminatorValue); } },
                { "avatar", n => { Avatar = n.GetObjectValue<global::Immich.Client.Models.AvatarUpdate>(global::Immich.Client.Models.AvatarUpdate.CreateFromDiscriminatorValue); } },
                { "cast", n => { Cast = n.GetObjectValue<global::Immich.Client.Models.CastUpdate>(global::Immich.Client.Models.CastUpdate.CreateFromDiscriminatorValue); } },
                { "download", n => { Download = n.GetObjectValue<global::Immich.Client.Models.DownloadUpdate>(global::Immich.Client.Models.DownloadUpdate.CreateFromDiscriminatorValue); } },
                { "emailNotifications", n => { EmailNotifications = n.GetObjectValue<global::Immich.Client.Models.EmailNotificationsUpdate>(global::Immich.Client.Models.EmailNotificationsUpdate.CreateFromDiscriminatorValue); } },
                { "folders", n => { Folders = n.GetObjectValue<global::Immich.Client.Models.FoldersUpdate>(global::Immich.Client.Models.FoldersUpdate.CreateFromDiscriminatorValue); } },
                { "memories", n => { Memories = n.GetObjectValue<global::Immich.Client.Models.MemoriesUpdate>(global::Immich.Client.Models.MemoriesUpdate.CreateFromDiscriminatorValue); } },
                { "people", n => { People = n.GetObjectValue<global::Immich.Client.Models.PeopleUpdate>(global::Immich.Client.Models.PeopleUpdate.CreateFromDiscriminatorValue); } },
                { "purchase", n => { Purchase = n.GetObjectValue<global::Immich.Client.Models.PurchaseUpdate>(global::Immich.Client.Models.PurchaseUpdate.CreateFromDiscriminatorValue); } },
                { "ratings", n => { Ratings = n.GetObjectValue<global::Immich.Client.Models.RatingsUpdate>(global::Immich.Client.Models.RatingsUpdate.CreateFromDiscriminatorValue); } },
                { "sharedLinks", n => { SharedLinks = n.GetObjectValue<global::Immich.Client.Models.SharedLinksUpdate>(global::Immich.Client.Models.SharedLinksUpdate.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Immich.Client.Models.TagsUpdate>(global::Immich.Client.Models.TagsUpdate.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Immich.Client.Models.AlbumsUpdate>("albums", Albums);
            writer.WriteObjectValue<global::Immich.Client.Models.AvatarUpdate>("avatar", Avatar);
            writer.WriteObjectValue<global::Immich.Client.Models.CastUpdate>("cast", Cast);
            writer.WriteObjectValue<global::Immich.Client.Models.DownloadUpdate>("download", Download);
            writer.WriteObjectValue<global::Immich.Client.Models.EmailNotificationsUpdate>("emailNotifications", EmailNotifications);
            writer.WriteObjectValue<global::Immich.Client.Models.FoldersUpdate>("folders", Folders);
            writer.WriteObjectValue<global::Immich.Client.Models.MemoriesUpdate>("memories", Memories);
            writer.WriteObjectValue<global::Immich.Client.Models.PeopleUpdate>("people", People);
            writer.WriteObjectValue<global::Immich.Client.Models.PurchaseUpdate>("purchase", Purchase);
            writer.WriteObjectValue<global::Immich.Client.Models.RatingsUpdate>("ratings", Ratings);
            writer.WriteObjectValue<global::Immich.Client.Models.SharedLinksUpdate>("sharedLinks", SharedLinks);
            writer.WriteObjectValue<global::Immich.Client.Models.TagsUpdate>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
