// <auto-generated/>
#pragma warning disable CS0618
using Immich.Client.Map.Markers;
using Immich.Client.Map.ReverseGeocode;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Client.Map
{
    /// <summary>
    /// Builds and executes requests for operations under \map
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The markers property</summary>
        public global::Immich.Client.Map.Markers.MarkersRequestBuilder Markers
        {
            get => new global::Immich.Client.Map.Markers.MarkersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reverseGeocode property</summary>
        public global::Immich.Client.Map.ReverseGeocode.ReverseGeocodeRequestBuilder ReverseGeocode
        {
            get => new global::Immich.Client.Map.ReverseGeocode.ReverseGeocodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Map.MapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.Map.MapRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/map", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
