// <auto-generated/>
#pragma warning disable CS0618
using Immich.Client.SystemMetadata.AdminOnboarding;
using Immich.Client.SystemMetadata.ReverseGeocodingState;
using Immich.Client.SystemMetadata.VersionCheckState;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Immich.Client.SystemMetadata
{
    /// <summary>
    /// Builds and executes requests for operations under \system-metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemMetadataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The adminOnboarding property</summary>
        public global::Immich.Client.SystemMetadata.AdminOnboarding.AdminOnboardingRequestBuilder AdminOnboarding
        {
            get => new global::Immich.Client.SystemMetadata.AdminOnboarding.AdminOnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reverseGeocodingState property</summary>
        public global::Immich.Client.SystemMetadata.ReverseGeocodingState.ReverseGeocodingStateRequestBuilder ReverseGeocodingState
        {
            get => new global::Immich.Client.SystemMetadata.ReverseGeocodingState.ReverseGeocodingStateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versionCheckState property</summary>
        public global::Immich.Client.SystemMetadata.VersionCheckState.VersionCheckStateRequestBuilder VersionCheckState
        {
            get => new global::Immich.Client.SystemMetadata.VersionCheckState.VersionCheckStateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.SystemMetadata.SystemMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemMetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system-metadata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Immich.Client.SystemMetadata.SystemMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemMetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system-metadata", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
